theme: jekyll-theme-merlot
repository: sxnwflkk/daily_routines

github: [metadata]
kramdown:
   input: GFM
   hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate


lsi: false
safe: true
source: /home/sxnwlfkk/heyb0ss/mysrc/daily_routines_android/docs
incremental: false
highlighter: rouge
gist:
 noscript: false
kramdown:
 math_engine: mathjax
