# theme: jekyll-theme-merlot
theme: jekyll-theme-minimal

repository: sxnwlfkk/daily_routines
title: Daily Routines
description: Android app for maintaining everyday and time sensitive routines
author: sxnwlfkk
author_email: sxnwlfkk@gmail.com

baseurl: /daily_routines

github:
  repository_name: daily_routines
  owner_name: sxnwlfkk
  owner_url: https://github.com/sxnwlfkk
kramdown:
   input: GFM
   hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate

footer-links:
  github: sxnwlfkk/daily_routines

lsi: false
safe: true
source: /home/sxnwlfkk/heyb0ss/mysrc/daily_routines_android/docs
incremental: false
highlighter: rouge
gist:
 noscript: false
kramdown:
 math_engine: mathjax

exclude:
  - Gemfile
  - Gemfile.lock
